export const today = new Date().toISOString().split("T")[0];
// const today_date = new Date();
// export const today =
//   `${today_date.getDate()}.${today_date.getMonth()}.${today_date.getFullYear()}`;

export const MAX_DIAMETER = 300; // [cm]
export const MAX_DISTANCE = 25; // [m]
export const MAX_LENGTH = 50; // [m]
export const MIN_DIAMETER_1 = 7; // [cm]
export const MIN_LENGTH_1 = 2; // [m]
export const MIN_DIAMETER_2 = 36; // [cm]
export const MIN_LENGTH_2 = 0.5; // [m]

export const decay_states = [1, 2, 3, 4, 5];

// Todo: load from file
export const tree_ids = [
  1,
  2,
  3,
  4,
  5,
  1200,
];

// Backup data, in case data cannot loaded from a file
// This is sorted by ID
export const team = [
  { id: 8, name: "Gast" },
  { id: 2, name: "Jonas Stillhard" },
  { id: 5, name: "Zivi" },
  { id: 7, name: "Jens Nitzsche" },
  { id: 1, name: "Gilbert Projer" },
  { id: 9, name: "Iza Murzynowska" },
  { id: 6, name: "Aushilfe" },
  { id: 10, name: "Carl Anderson" },
].sort((a, b) => a.id - b.id);

export const tree_species = [
  { id: -1, name: "Keine Angabe" },
  { id: 411, name: "Fagus sylvatica L." },
  { id: 561, name: "Carpinus betulus L." },
  { id: 441, name: "Acer pseudoplatanus L." },
  { id: 440, name: "Acer L." },
  { id: 442, name: "Acer platanoides L." },
  { id: 443, name: "Acer campestre L." },
  { id: 471, name: "Betula pendula Roth" },
  { id: 121, name: "Abies alba Mill." },
  { id: 101, name: "Picea abies (L.) H. Karst." },
  { id: 530, name: "Salix L." },
  { id: 534, name: "Salix caprea L." },
  { id: 531, name: "Salix viminalis L." },
  { id: 540, name: "Salix purpurea L." },
  { id: 521, name: "Prunus avium (L.) L." },
  { id: 551, name: "Sorbus aria (L.) Crantz" },
  { id: 552, name: "Sorbus aucuparia L." },
  { id: 422, name: "Quercus petraea (Matt.) Liebl." },
  { id: 420, name: "Quercus L." },
  { id: 421, name: "Quercus robur L." },
  { id: 510, name: "Ulmus L." },
  { id: 511, name: "Ulmus glabra Huds." },
  { id: 512, name: "Ulmus minor Mill." },
  { id: 513, name: "Ulmus laevis Pall." },
  { id: 901, name: "Corylus avellana L." },
  { id: 905, name: "Sambucus nigra L." },
  { id: 906, name: "Sambucus racemosa L." },
  { id: 100, name: "Picea sp." },
  { id: 102, name: "Picea omorika (Panc.) Purk." },
  { id: 103, name: "Picea pungens Engelm." },
  { id: 104, name: "Picea sitchensis (Bong.) Carriere" },
  { id: 105, name: "Picea mariana (Mill.) Britton, Sterns et Poggenb." },
  { id: 107, name: "Picea glehni (F. Schmidt) Mast." },
  { id: 120, name: "Abies Mill." },
  { id: 122, name: "Abies amabilis (Douglas ex Loudon) Douglas ex Forbes" },
  { id: 123, name: "Abies balsamea (L.) Mill." },
  { id: 124, name: "Abies concolor (Gordon et Glend.) Lindl. ex Hildebr." },
  { id: 125, name: "Abies concolor Lowiana Grp." },
  { id: 126, name: "Abies firma Siebold et Zucc." },
  { id: 127, name: "Abies grandis (Dougl. ex D.Don) Lindl." },
  { id: 128, name: "Abies homolepis Siebold et Zucc." },
  { id: 129, name: "Abies nordmanniana (Steven) Spach" },
  { id: 130, name: "Abies procera Rehder" },
  { id: 131, name: "Abies sachalinensis (F. Schmidt) Mast." },
  { id: 132, name: "Abies veitchii Lindl." },
  { id: 140, name: "Pinus L." },
  { id: 141, name: "Pinus sylvestris L." },
  { id: 142, name: "Pinus mugo Turra ssp. mugo" },
  { id: 143, name: "Pinus mugo Turra ssp. pumilio (Haenke) Franco" },
  { id: 144, name: "Pinus cembra L." },
  { id: 145, name: "Pinus nigra Arnold" },
  { id: 146, name: "Pinus peuce Griseb." },
  { id: 147, name: "Pinus strobus L." },
  { id: 148, name: "Pinus contorta Douglas ex Loudon" },
  { id: 149, name: "Pinus ponderosa Dougl. ex P. et C. Lawson" },
  { id: 150, name: "Pinus resinosa Aiton" },
  { id: 151, name: "Pinus rigida Mill." },
  { id: 152, name: "Pinus wallachiana A. B. Jacks." },
  { id: 153, name: "Pinus banksiana Lamb." },
  { id: 160, name: "Larix Mill." },
  { id: 161, name: "Larix decidua Mill." },
  { id: 162, name: "Larix kaempferi (Lamb.) Carriere" },
  { id: 163, name: "Larix laricina (Du Roi) K. Koch" },
  { id: 164, name: "Larix x eurolepis Henry" },
  { id: 181, name: "Pseudotsuga menziesii (Mirb.) Franco" },
  { id: 191, name: "Juniperus communis L." },
  { id: 201, name: "Taxus baccata L." },
  { id: 211, name: "Calocedrus decurrens (Torr.) Florin" },
  { id: 221, name: "Cedrus deodara (Roxb.) G. Don" },
  { id: 231, name: "Chamaecyparis Spach." },
  { id: 241, name: "Cryptomeria japonica D. Don." },
  { id: 251, name: "Metasequoia glyptostroboides Hu et W.C. Cheng" },
  { id: 252, name: "Sequoiadendron giganteum (Lindl.) Buchholz" },
  { id: 253, name: "Sequoia sempervirens (D. Don) Endl." },
  { id: 261, name: "Thuja plicata Donn ex D. Don" },
  { id: 271, name: "Tsuga heterophylla (Raf.) Sarg." },
  { id: 390, name: "ubriges Nadelholz" },
  { id: 410, name: "Fagus L." },
  { id: 412, name: "Fagus orientalis Lipsky" },
  { id: 423, name: "Quercus pubescens Willd." },
  { id: 424, name: "Quercus cerris L." },
  { id: 425, name: "Quercus rubra L." },
  { id: 426, name: "Quercus castaneifolia C.A. Mey." },
  { id: 427, name: "Quercus palustris Munchh." },
  { id: 430, name: "Fraxinus L." },
  { id: 431, name: "Fraxinus excelsior L." },
  { id: 432, name: "Fraxinus ornus L." },
  { id: 433, name: "Fraxinus americana L." },
  { id: 444, name: "Acer opalus Mill." },
  { id: 446, name: "Acer monspessulanum L." },
  { id: 450, name: "Populus L." },
  { id: 451, name: "Populus alba L." },
  { id: 452, name: "Populus x canescens (Aiton) Sm" },
  { id: 453, name: "Populus nigra L." },
  { id: 454, name: "Populus tremula L." },
  { id: 455, name: "Populus balsamifera L." },
  { id: 456, name: "Populus x canadensis Moench" },
  { id: 460, name: "Castanea Mill." },
  { id: 461, name: "Castanea sativa Mill." },
  { id: 462, name: "Castanea crenata Sieb. et Zucc." },
  { id: 463, name: "Castanea mollissima Blume" },
  { id: 468, name: "Castanea Mill. X" },
  { id: 470, name: "Betula L." },
  { id: 472, name: "Betula pubescens Ehrh." },
  { id: 473, name: "Betula humilis Schrank" },
  { id: 474, name: "Betula nana L." },
  { id: 476, name: "Betula platyphylla var. Japonica (Miq.) Hara" },
  { id: 481, name: "Juglans regia L." },
  { id: 482, name: "Juglans nigra L." },
  { id: 490, name: "Alnus Mill." },
  { id: 491, name: "Alnus glutinosa (L.) Gaertn." },
  { id: 492, name: "Alnus incana (L.) Moench" },
  { id: 493, name: "Alnus viridis (Chaix) DC" },
  { id: 500, name: "Tilia L." },
  { id: 501, name: "Tilia cordata Mill." },
  { id: 502, name: "Tilia platyphyllos Scop." },
  { id: 520, name: "Prunus L." },
  { id: 522, name: "Prunus padus L." },
  { id: 523, name: "Prunus spinosa L." },
  { id: 524, name: "Prunus cerasus L." },
  { id: 525, name: "Prunus mahaleb L." },
  { id: 526, name: "Prunus serotina Ehrh." },
  { id: 532, name: "Salix alba L." },
  { id: 533, name: "Salix triandra L. ssp. triandra (Salix amygdalina)" },
  { id: 535, name: "Salix cinerea L." },
  { id: 536, name: "Salix daphnoides Vill." },
  { id: 537, name: "Salix elaeagnos Scop." },
  { id: 538, name: "Salix fragilis L." },
  { id: 539, name: "Salix pentandra L." },
  { id: 550, name: "Sorbus L." },
  { id: 553, name: "Sorbus domestica L." },
  { id: 554, name: "Sorbus torminalis (L.) Crantz" },
  { id: 555, name: "Sorbus chamaemespilus (L.) Crantz" },
  { id: 556, name: "Sorbus x hybrida L." },
  { id: 557, name: "Sorbus latifolia" },
  { id: 558, name: "Sorbus mougeotii" },
  { id: 571, name: "Celtis australis L." },
  { id: 581, name: "Ostrya carpinifolia Scop." },
  { id: 591, name: "Ilex aquifolium L." },
  { id: 601, name: "Laburnum anagyroides Medik." },
  { id: 602, name: "Laburnum alpinum (Mill.) Brecht. et J. Presl" },
  { id: 611, name: "Malus sylvestris (L.) Mill." },
  { id: 621, name: "Pyrus pyraster Burgsd." },
  { id: 631, name: "Mespilus germanica L." },
  { id: 701, name: "Robinia pseudoacacia L." },
  { id: 711, name: "Carya ovata (Mill.) K. Koch" },
  { id: 721, name: "Platanus x hispanica Munchh." },
  { id: 731, name: "Aesculus hippocastanum L." },
  { id: 741, name: "Liriodendron tulipifera L." },
  { id: 751, name: "Cercidiphyllum japonicum Sieb. et Zucc." },
  { id: 761, name: "Ailanthus altissima" },
  { id: 771, name: "Cinnamomum camphora" },
  { id: 781, name: "Rhus typhina" },
  { id: 800, name: "ubriges Laubholz" },
  { id: 902, name: "Amelanchier ovalis Medik." },
  { id: 903, name: "Berberis vulgaris L." },
  { id: 904, name: "Buxus sempervirens L." },
  { id: 907, name: "Cytisus Desf." },
  { id: 908, name: "Cytis scoparius ssp. scoparius" },
  { id: 909, name: "Viburnum lantana L." },
  { id: 910, name: "Viburnum opulus L." },
  { id: 911, name: "Clematis vitalba L." },
  { id: 912, name: "Cornus mas L." },
  { id: 913, name: "Cornus sanguinea L." },
  { id: 914, name: "Cotoneaster integerrimus Medik." },
  { id: 915, name: "Cotoneaster tomentosus (Guss.) K. Koch" },
  { id: 916, name: "Crataegus laevigata (Poir) DC." },
  { id: 917, name: "Crataegus monogyna Jacq." },
  { id: 918, name: "Evonymus europaeus L." },
  { id: 919, name: "Evonymus latifolius (L.) Mill." },
  { id: 920, name: "Hedera helix L." },
  { id: 921, name: "Hippophae rhamnoides L." },
  { id: 922, name: "Juniperus communis ssp. alpina (Suter) Celak." },
  { id: 923, name: "Juniperus sabina L." },
  { id: 924, name: "Ligustrum vulgare L." },
  { id: 925, name: "Lonicera alpigena L." },
  { id: 926, name: "Lonicera caerulea L." },
  { id: 927, name: "Lonicera nigra L." },
  { id: 928, name: "Lonicera periclymenum L." },
  { id: 929, name: "Lonicera xylosteum L." },
  { id: 930, name: "Frangula alnus Mill." },
  { id: 931, name: "Rhamnus alpina L." },
  { id: 932, name: "Rhamnus cathartica L." },
  { id: 933, name: "Rhamnus pumila Turra" },
  { id: 934, name: "Rhamnus saxatilis Jacq." },
  { id: 935, name: "Rosa spec." },
  { id: 936, name: "Buddleia sp." },
  { id: 937, name: "Chamaerops humilis" },
  { id: 938, name: "Cotinus coggygria" },
  { id: 939, name: "Crateagus sp." },
  { id: 940, name: "Ficus carica" },
  { id: 942, name: "Ribes sp." },
  { id: 943, name: "Staphylea pinnata" },
  { id: 999, name: "nicht bestimmbar, tot" },
].sort((a, b) => a.id - b.id);
